CREATE TABLE [CATALOGO].[EDICION]
(
[ID_EDICION] [int] NOT NULL,
[ID_LIBRO] [int] NOT NULL,
[ANIO_EDICION] [int] NOT NULL,
[PRECIO_EDICION] [real] NOT NULL,
[ISBN] [bigint] NOT NULL
) ON [BS_CATALOGO]
GO
ALTER TABLE [CATALOGO].[EDICION] ADD CONSTRAINT [PK_EDICION] PRIMARY KEY NONCLUSTERED  ([ID_EDICION]) ON [BS_CATALOGO]
GO
ALTER TABLE [CATALOGO].[EDICION] ADD CONSTRAINT [FK_EDICION_RELATIONS_LIBRO] FOREIGN KEY ([ID_LIBRO]) REFERENCES [CATALOGO].[LIBRO] ([ID_LIBRO])
GO
