CREATE TABLE [CATALOGO].[AUTOR_LIBRO]
(
[ID_AUTOR] [int] NOT NULL,
[ID_LIBRO] [int] NOT NULL
) ON [BS_CATALOGO]
GO
ALTER TABLE [CATALOGO].[AUTOR_LIBRO] ADD CONSTRAINT [PK_AUTOR_LIBRO] PRIMARY KEY CLUSTERED  ([ID_AUTOR], [ID_LIBRO]) ON [BS_CATALOGO]
GO
ALTER TABLE [CATALOGO].[AUTOR_LIBRO] ADD CONSTRAINT [FK_AUTOR_LI_RELATIONS_AUTOR] FOREIGN KEY ([ID_AUTOR]) REFERENCES [CATALOGO].[AUTOR] ([ID_AUTOR])
GO
ALTER TABLE [CATALOGO].[AUTOR_LIBRO] ADD CONSTRAINT [FK_AUTOR_LI_RELATIONS_LIBRO] FOREIGN KEY ([ID_LIBRO]) REFERENCES [CATALOGO].[LIBRO] ([ID_LIBRO])
GO
