CREATE TABLE [CATALOGO].[INFO_LIBRO]
(
[TITULO_LIBRO] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IDIOMA_LIBRO] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ID_LIBRO] [int] NOT NULL,
[ID_EDICION] [int] NOT NULL,
[ANIO_EDICION] [int] NOT NULL,
[PRECIO_EDICION] [real] NOT NULL,
[ISBN] [bigint] NOT NULL
) ON [BS_CATALOGO]
GO
