CREATE TABLE [CATALOGO].[AUTOR]
(
[ID_AUTOR] [int] NOT NULL,
[FECHA_NAC] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[NACIONALIDAD] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[NOMBRE_AUTOR] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[APELLIDO_AUTOR] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [BS_CATALOGO]
GO
ALTER TABLE [CATALOGO].[AUTOR] ADD CONSTRAINT [PK_AUTOR] PRIMARY KEY NONCLUSTERED  ([ID_AUTOR]) ON [BS_CATALOGO]
GO
