CREATE TABLE [CATALOGO].[LIBRO]
(
[TITULO_LIBRO] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IDIOMA_LIBRO] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ID_LIBRO] [int] NOT NULL
) ON [BS_CATALOGO]
GO
ALTER TABLE [CATALOGO].[LIBRO] ADD CONSTRAINT [PK_LIBRO] PRIMARY KEY NONCLUSTERED  ([ID_LIBRO]) ON [BS_CATALOGO]
GO
