CREATE TABLE [VENTAS].[DETALLE_COMPRA]
(
[ID_DETALLE] [int] NOT NULL,
[ID_COMPRA] [int] NOT NULL,
[ID_EDICION] [int] NOT NULL,
[PRECIO_UNITARIO] [real] NOT NULL,
[CANTIDAD] [int] NOT NULL,
[DESCRIPCION] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [BS_VENTAS]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [VENTAS].[ACTUALIZAR_MONTO]
ON [VENTAS].[DETALLE_COMPRA]
AFTER INSERT
AS
BEGIN
	DECLARE @PRECIO_UNITARIO FLOAT, @CANTIDAD INT, @ID_COMPRA INT
	SELECT @PRECIO_UNITARIO = PRECIO_UNITARIO, @CANTIDAD = CANTIDAD, @ID_COMPRA = ID_COMPRA
	FROM INSERTED;

	UPDATE VENTAS.COMPRA
	SET MONTO_TOTAL = MONTO_TOTAL + (@CANTIDAD * @PRECIO_UNITARIO)
	WHERE ID_COMPRA = @ID_COMPRA;
END
GO
ALTER TABLE [VENTAS].[DETALLE_COMPRA] ADD CONSTRAINT [PK_DETALLE_COMPRA] PRIMARY KEY NONCLUSTERED  ([ID_DETALLE]) ON [BS_VENTAS]
GO
ALTER TABLE [VENTAS].[DETALLE_COMPRA] ADD CONSTRAINT [FK_DETALLE_COMPRA_RELATIONS_COMPRA] FOREIGN KEY ([ID_COMPRA]) REFERENCES [VENTAS].[COMPRA] ([ID_COMPRA])
GO
ALTER TABLE [VENTAS].[DETALLE_COMPRA] ADD CONSTRAINT [FK_DETALLE_COMPRA_RELATIONS_EDICION] FOREIGN KEY ([ID_EDICION]) REFERENCES [CATALOGO].[EDICION] ([ID_EDICION])
GO
