CREATE TABLE [VENTAS].[COMPRA_LIBRO]
(
[ID_COMPRA] [int] NOT NULL,
[ID_LIBRO] [int] NOT NULL
) ON [BS_VENTAS]
GO
ALTER TABLE [VENTAS].[COMPRA_LIBRO] ADD CONSTRAINT [PK_COMPRA_LIBRO] PRIMARY KEY CLUSTERED  ([ID_COMPRA], [ID_LIBRO]) ON [BS_VENTAS]
GO
ALTER TABLE [VENTAS].[COMPRA_LIBRO] ADD CONSTRAINT [FK_COMPRA_L_RELATIONS_COMPRA] FOREIGN KEY ([ID_COMPRA]) REFERENCES [VENTAS].[COMPRA] ([ID_COMPRA])
GO
ALTER TABLE [VENTAS].[COMPRA_LIBRO] ADD CONSTRAINT [FK_COMPRA_L_RELATIONS_LIBRO] FOREIGN KEY ([ID_LIBRO]) REFERENCES [CATALOGO].[LIBRO] ([ID_LIBRO])
GO
