CREATE TABLE [VENTAS].[TARJETA_CREDITO]
(
[NUM_TARJETA] [bigint] NOT NULL,
[EMISOR] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FECHA_VENCIMIENTO] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[COD_SEGURIDAD] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [BS_VENTAS]
GO
ALTER TABLE [VENTAS].[TARJETA_CREDITO] ADD CONSTRAINT [PK_TARJETA] PRIMARY KEY NONCLUSTERED  ([NUM_TARJETA]) ON [BS_VENTAS]
GO
