CREATE DATABASE BOOKSTORE
ON PRIMARY(NAME = 'PRIMARY_DATA',
FILENAME = N'E:\FileGroups_BookStore\PRIMARY_DATA.mdf', 
SIZE = 10MB, 
MAXSIZE = 50MB, 
FILEGROWTH = 1MB),

FILEGROUP BS_CATALOGO
(NAME ='BS_CATALOGO1',
FILENAME = N'E:\FileGroups_BookStore\BS_CATALOGO1.ndf', 
SIZE = 10MB, 
MAXSIZE = 50MB, 
FILEGROWTH = 1MB),

(NAME ='BS_CATALOGO2',
FILENAME = N'E:\FileGroups_BookStore\BS_CATALOGO2.ndf', 
SIZE = 10MB, 
MAXSIZE = 50MB, 
FILEGROWTH = 1MB),

FILEGROUP BS_VENTAS 
( NAME = 'BS_VENTAS1', 
FILENAME = N'E:\FileGroups_BookStore\BS_VENTAS1.ndf', 
SIZE = 1MB, 
MAXSIZE = 50MB, 
FILEGROWTH = 1MB),

 ( NAME = 'BS_VENTAS2', 
 FILENAME = N'E:\FileGroups_BookStore\BS_VENTAS2.ndf', 
 SIZE = 1MB, 
 MAXSIZE = 50MB, 
 FILEGROWTH = 1MB)
 
 LOG ON 
 ( NAME ='LOG', 
 FILENAME = N'G:\LOG_BookStore\LOG.ldf', 
 SIZE = 1MB, 
 MAXSIZE = 50MB, 
 FILEGROWTH = 1MB); 
  
  GO